### ISSUE TITLE
Action does not support dynamic selects

### ISSUE THREAD

**Issue by cedricbirdly** [seratch/jslack#52]
Hello!

The Action class misses two attributes to support the dynamic menus:
 private String dataSource;
private int minQueryLength;

Could you add them?

see https://api.slack.com/docs/message-menus#populate_message_menus_dynamically

**Comment by cedricbirdly** [comment]
Thanks a lot! Could you please update the maven version?

**Comment by seratch** [comment]
I just released 1.0.19.

**Comment by cedricbirdly** [comment]
Hey! Not sure if normal, but still can't see 1.0.19 in maven repository :(

**Comment by seratch** [comment]
Ah, sorry. The release was not completed. It's done now. https://oss.sonatype.org/content/repositories/releases/com/github/seratch/jslack/1.0.19/
